### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by eson57** [abertschi/sailfish-wlan-keyboard#11]
Is it possible to add translation strings for cover page? Maybe also for web interface?

![screenshot-14-05-15-09-20-51_s](https://cloud.githubusercontent.com/assets/2996154/7627907/eb88f926-fa1c-11e4-9cce-d968147954ac.png)
![2015-05-14_092741](https://cloud.githubusercontent.com/assets/2996154/7627914/fe8127e2-fa1c-11e4-9203-ba09d30ab333.png)

**Comment by abertschi** [comment]
I just added them in the CoverPage.
Feel free to create a pull request and translate the CoverPage labels to your desired language.
About translations for the react ui, there is an issue here: #9.

**Comment by eson57** [comment]
Thanks!
