### ISSUE TITLE
Clipboard only has the last character

### ISSUE THREAD

**Issue by strayobject** [abertschi/sailfish-wlan-keyboard#16]
I don't know if it's a bug or supposed to be a feature. When I type in the browser, clipboard only has the last character and not the full sentence.
I can imagine this mode to be working well for headless mode, but it should be disabled for clipboard.

Running version: 0.3.0-19-ge745435
mode: clipboard

Could someone please verify?

**Comment by Kiachma** [comment]
Experiencing the same problem

**Comment by abertschi** [comment]
Can you list the necessary steps to reproduce the behaviour?

**Comment by strayobject** [comment]
There is really nothing to it.
Open up the app, start the server, open up a browser, go to url, start typing, (optionally hit enter)

This time round the only thing I get is letter "a" in the clipboard - even though no "a" was present in the text entered.

This is not browser specific, neither does it relate to the plugins installed.
Tested on Ubuntu 14.04:
FF 38 with adblock, noscript, etc
Chromium 41 with adblock
Vivalidi without any plugins

I will try on a mac & windows tomorrow (in about 10hrs) - if necessary.

**Comment by eson57** [comment]
I can confirm, it's the same on Windows, so it shouldn't be related to desktop platform.

**Comment by ghost** [comment]
Yes on my MacBook pro i have the same problem it only let me paste 2 charactors and not the full text i have put into the desktop platform.

**Comment by abertschi** [comment]
I will take a closer look during the upcoming weekend. In the meantime, what someone could do is to verify the described behavior in the latest version, 0.3.1

Available on openrepos 
https://openrepos.net/content/abertschi/sailfish-wlan-keyboard

Please make sure the deinstall both the headless-keyboard layout and the app beforehand.
Thanks for your support.

**Comment by ghost** [comment]
abertschi, i was using the lasted version i have also try the older version every version has the same problem.

**Comment by eson57** [comment]
The bug is there, in v0.3.1. Even before installing headless-keyboard layout.

**Comment by abertschi** [comment]
Released version 0.3.2, see release https://github.com/abertschi/sailfish-wlan-keyboard/releases/tag/v-0.3.2

**Comment by ghost** [comment]
Ok download the new version and installed it, now clipboard mode works perfect !

**Comment by abertschi** [comment]
I updated openrepos with the new version.
A new harbour store version will be available once issue  #13 and #15 are done.
