### ISSUE TITLE
Wont support input chinese char

### ISSUE THREAD

**Issue by TMavica** [abertschi/sailfish-wlan-keyboard#17]

**Comment by abertschi** [comment]
Hi there, would you mind describing what exactly does not work with Chinese characters and perhaps listing a few steps to reproduce the failing behaviour? Thanks

**Comment by TMavica** [comment]
Enter in browser, no word show in notes
english working fine

**Comment by abertschi** [comment]
@TMavica, please name some Chinese characters that seem not to work.

**Comment by TMavica** [comment]
all cant. but relative to my input method

**Comment by abertschi** [comment]
see #18
