### ISSUE TITLE
Accented/special characters not displayed

### ISSUE THREAD

**Issue by fravaccaro** [abertschi/sailfish-wlan-keyboard#18]
I have troubles in displaying accented characters èòàù and special characters, like £ and € (no problems with $ though).

My keyboard layout is set to Italian.

**Comment by abertschi** [comment]
The keystrokes seem to be transmitted to the Qt app but not applied by the [headless-keyboard layout](https://github.com/abertschi/sailfish-headless-keyboard-dbus)

Issue #17 might be related to this one.

**Comment by aAXEe** [comment]
Same here. The special characters like ä, ü, ö, ß work only with the clipboad mode but are not typed in the headless mode. So I guess that the problem is in the headless-keyboard layout?

**Comment by abertschi** [comment]
There is an encoding issue in the keyboard layout. Ascii is used for all keystrokes. Therefore characters greater than 127 will result in an exception. Thats why the issue does not appear in the English language. I will try to fix it until the end of next week.

**Comment by abertschi** [comment]
Error causing debug statements removed. abertschi/sailfish-headless-keyboard-dbus@d41f19d

**Comment by abertschi** [comment]
Tested with various non ascii chars. Chinese as well #17. Should be fine now.
