### ISSUE TITLE
not working in headless mode with os version 1.1.6.27

### ISSUE THREAD

**Issue by abertschi** [abertschi/sailfish-wlan-keyboard#20]
The headless mode does not work anymore with the new OS version 1.1.6.27.

**Comment by aAXEe** [comment]
It works at my phone. Both clipboard and headless.
I installed the app some time before the update.

**Comment by abertschi** [comment]
New feature about Clipboard-Sync #22 tested app and verified its compatibility for OS version 1.1.9.28.
