### ISSUE TITLE
wlan-keyboard might be related to blocking the clipboard

### ISSUE THREAD

**Issue by florianjacob** [abertschi/sailfish-wlan-keyboard#7]
Yesterday morning, I installed the wlan-keyboard app, pasted some texts and all worked fine as expected. :) But yesterday evening, I still had the last text from morning in my clipboard and tried to copy some text from the notes app into the clipboard, but instead, the old clipboard got pasted over the text. It turned out that I was completely unable to overwrite or delete the clipboard contents on my phone, only a reboot helped.

I tried to reproduce it now, but I couldn't. I still wanted to let you know, though.

(I actually lost that quite important text I wanted to copy due to the notes app not having an undo function, but that's another story: https://together.jolla.com/question/53726/request-undo-option-in-notes-app/ )

**Comment by abertschi** [comment]
Please reopen the issue again when you can reproduce the behaviour. Otherwise, there is not much I can do.  I followed your usecase on my device but couldn't reproduce is neither.

**Comment by florianjacob** [comment]
I guess it doesn't happen that easy then, thanks for re-checking. I'll watch out from now on, so in case it happens again, I'll be more prepared with more exact steps to reproduce and logging output.

Thanks for making this app, and for making it open source. :smile:

**Comment by abertschi** [comment]
@florianjacob, thanks for using the app :smile:
